### ISSUE TITLE
InfluxDB Flux integration punch list

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#10374]
- [x] add / integrate metrics (#10389)
- [x] add appropriate unit / integration tests (#10389)
- [x] configuration options (enable / disable), others? (#10389)
- [x] verify query / resource cleanup 
https://github.com/influxdata/flux/issues/57
- [x] verify performance (i.e. basic queries execute in some reasonable time)
- [x] update API endpoint to `/api/v2/query` (#10389) per [swagger](https://github.com/influxdata/platform/blob/ea4c08b327efa62f870eb95ee217361e232e56dc/http/swagger.yml#L1642)
- [x] add Flux support to `influx` CLI (#10407)
- [x] Update CHANGELOG with reference to `influx` CLI improvements (#10413)

----

## Platform compatibility

Notes per discussion with @pauldix 

* if the `organizationId=<id>` query parameter is specified when calling `/api/v2/query`, it should be allowed, but ignored
* enhance the [existing InfluxDB OSS `influx` CLI command][influx] to support `flux`
    * Issue #10407 covers the requirements

**NOTE:** Rationale for not using [`influx (repl|query)` commands from `platform`][platform_influx] is to reduce user confusion and avoid having to explain and / or configure organizations.

[influx]: https://github.com/influxdata/influxdb/tree/master/cmd/influx
[platform_influx]: https://github.com/influxdata/platform/tree/master/cmd/influx

**Comment by nathanielc** [comment]
The compatibility bits look good to me.

**Comment by e-dard** [comment]
This work is now done.
