### ISSUE TITLE
connect UI labels to the backend API

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#10999]
we need to connect the front end capability to the labels api and remove anything hardcoded

- [x] Check status on implementing global `/labels` endpoint. The mock api calls in `src/configuration/api` no longer accept an org and expect to use `/api/labels` instead of `/api/orgs/{orgID}/labels`. see progress at https://github.com/influxdata/influxdb/pull/11198
- [x] Remove/discuss label `resourceID`s from `cur_swagger.yml`. See https://github.com/influxdata/influxdb/pull/11198#issuecomment-455626434
- [ ] Add fetched resourceID to labels
- [x] Update labels generated client after `/labels` endpoint work is complete. Update cur_swagger descriptions with http/swagger for labels
- [x] Update `src/configuration/api` and `src/shared/apis/labels` to use generated client instead of mocks. Determine if these `getLabels` utils are using the same endpoint.

----
> - [ ] Nice to have: discuss updating dashboards/labels and similar endpoints to allow **adding** and **removing** multiple labels in one post or delete

**Comment by russorat** [comment]
this story should be broken down so that additional people can work on it. @OfTheDelmer
