### ISSUE TITLE
Ability to select which series is displayed in a Single Stat or Gauge cell

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#11541]
This could be a simple dropdown in the top of the options:

<img width="413" alt="screen shot 2019-01-24 at 11 14 43 am" src="https://user-images.githubusercontent.com/2433762/51702752-73036280-1fc9-11e9-845b-ff0b49d3964f.png">

**Comment by OfTheDelmer** [comment]
![kapture 2019-02-07 at 12 36 20](https://user-images.githubusercontent.com/4994741/52430951-36f5f480-2ad5-11e9-818a-fda1d5418b52.gif)

Selecting the `seriesKey` from a dropdown needs some design work to make the very long series key readable.

In order to complete this task currently, we need to do the following:

- [X] Update the `GaugeViewProperties` to store the `seriesSelections`:

 ```
type GaugeViewProperties struct {
	Type              string            `json:"type"`
	Queries           []DashboardQuery  `json:"queries"`
	Prefix            string            `json:"prefix"`
	Suffix            string            `json:"suffix"`
	ViewColors        []ViewColor       `json:"colors"`
	DecimalPlaces     DecimalPlaces     `json:"decimalPlaces"`
	Note              string            `json:"note"`
	ShowNoteWhenEmpty bool              `json:"showNoteWhenEmpty"`
	SeriesSelections  []SeriesSelection `json:"seriesSelections"`
}

// TableSelection represents the series selected for viewing
type SeriesSelection struct {
	Selected  bool   `json:"selected"`
	SeriesKey string `json:"seriesKey"`
}
 ```
- [X] Update the `GaugeChart`'s `lastValue` method to select either the last value from the spreadTables or find the `lastTime` and `value` for a selected `seriesKey`
- [ ] Update the `spreadTables`' key creation to ensure `seriesDescription['key']` is unique across query tabs.  *This might be tricky since the graph is currently only provided the tables and no queryTab info.*
- [X] Sync updated `SeriesSelections` on `componentUpdate` or `componentMount` to redux state to ensure the `GaugeOptions` displays the correct series in the dropdown.

----

However, storing the `seriesKey` as a string might impact the ease of the design of the dropdown in `GaugeOptions`, i.e. we may want to store the group key, tableName, columnName, and query tab index separately for rendering of the dropdown. Also, after some discussion with  @chnn we may want to determine the lifetime of such changes if we are going to be changing up query visualization rendering soon and what needs to be stored is going to change quite a bit.

**Comment by OfTheDelmer** [comment]
Alex and I did pair on the design for this and found that something like the hover legend on line graphs might suffice.

**Comment by chnn** [comment]
Closing in favor of more up to date #14121
