### ISSUE TITLE
Add the ability to add labels to telegraf configs

### ISSUE THREAD

**Issue by ischolten** [influxdata/influxdb#11612]
as a user,
i can add, remove, edit labels on a telegraf config from the telegraf config row

- [x] Add `GetLabels` to the Telegraf config pages (used for autocompletion of inline labels)
- [x] Add the InlineLabels to the telegraf config rows
- [x] Add actions for `addTelegrafLabelAsync` and `removeTelegrafLabelAsync` where the telegraf config is refetched after a labels change and updated in redux store rather than managing  `telegraf.labels` state directly. See the `addTaskLabelAsync` and `updateTask` actions
- [x] Add notifications copy for failed to add or remove telegraf label
- [x] Handle notifying in actions not in the telegraf row component (similar to `addTaskLabelAsync`)

--- 

- [ ] Update `Telegraf` to `ITelegraf`

- [ ] Select and render only telegraf labels that  don't have the `@influxdata` prefix using the selectors work.

**Comment by 121watts** [comment]
will find branch in progress and post here

**Comment by 121watts** [comment]
current work done on this located here: https://github.com/influxdata/influxdb/tree/feat/telegraf-configs-labels
