### ISSUE TITLE
use resource types with ILabel[]

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/influxdb#12243]
Remove labels `src/types/v2/labels` once the `@influxdata/influx` Labels have been updated.

- [x] Make `src/types/v2/labels` just re-export `ILabel` and `ILabel.properties` from `@influxdata/influx` 

- [x] Update `src/types/v2/dashboards` to extend the `IDashboard` which requires labels as well as other properties like `id`, `name`, etc
- [x] Update `src/types/v2/tasks` to extend the `ITask` which requires labels
- [ ] Update types to extend `IBucket` which requires labels

**Comment by OfTheDelmer** [comment]
For background the issue with other types is that `addLabel` and `removeLabel` on a resource will return type `ILabel`, but the `Dashboard.labels` were not type `ILabel[]`. This caused parts of the UI to coerce types from `Label` to `ILabel`.
