### ISSUE TITLE
Add Variables tab to config page

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#12255]
We are moving any kind of configuration workflows into the config page since that's where users tend to look first

- [ ] Create `Variables` tab within `Configuration` page
- [ ] Create `Variables` tab within `Configuration` navbar tab
- [ ] List variables across all orgs
- [ ] Add `Owner` column to table
- [ ] Variables page in `Configuration` should otherwise look the same as the org level variables page

**Comment by ebb-tide** [comment]
I wonder if we wouldn't also want to preserve the variables under the orgs page?
