### ISSUE TITLE
Cannot rename labels

### ISSUE THREAD

**Issue by mavarius** [influxdata/influxdb#12578]
Cannot rename labels

![LabelRenameBug](https://user-images.githubusercontent.com/11937365/54240731-1b1ead80-44dc-11e9-8480-2215cdf5542b.gif)

- [x] Await API update for label name updating: https://github.com/influxdata/influxdb/pull/12585
- [x] Regenerate client types and bump version
- [x] Change `updateLabel` action to take a `Label` and not just properties

**Comment by OfTheDelmer** [comment]
This is a remnant of when labels were indexed by `name`, but the API can be updated now to allow `name` to be part of the `LabelUpdate`.  Once the labels API is resolved we can fix this update form.

**Comment by OfTheDelmer** [comment]
- [ ] Await API update for label name updating: https://github.com/influxdata/influxdb/pull/12585
- [ ] Regenerate client types and bump version
- [ ] Change `updateLabel` action to take a `Label` and not just properties

**Comment by jademcgough** [comment]
@OfTheDelmer #12585 has been merged
