### ISSUE TITLE
Convert influxd binary to use the cobra CLI package

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#12602]
Future versions of the `influxd` binary will provide tooling via subcommands. To simplify adding these subcommands, migrate to the `cobra` CLI package. 

**TODOs:**

- [x] add `cobra` CLI package
- [x] add `run` subcommand the launches the influxd server
    - [x] If no subcommand is specified when executing `influxd`, the default will be to execute the `run` subcommand. 

----

Some examples of future commands include

* `influxd inspect` - analyze various data files created by InfluxDB
* `influxd gen` - generate data for testing
