### ISSUE TITLE
Update labels creation to include orgID

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/influxdb#12736]
- [x] Await API changes from https://github.com/influxdata/influxdb/pull/12734
- [ ] Regenerate client and update label wrappers to ensure `orgID` in `labels` properties, see https://github.com/influxdata/influxdb2-js/blob/master/src/types/index.ts#L8.
     * Note we should probably change the `name` and `ILabelProperties` arguments to an interface that's similar to the `LabelCreateRequest` interface. It should requires properties exist and include color. Maybe call it `ILabelCreateRequest` 
- [ ] Update to the latest client and migrate API and async actions calls with `labels.create` in the UI to include `orgID`

**Comment by OfTheDelmer** [comment]
Closed by https://github.com/influxdata/influxdb/pull/12751
