### ISSUE TITLE
Add create resource from this template button to templates view

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#12925]
- [x] Add `Create Button` to `TemplateCard` to trigger resource creation.
- [x] create an action to `createResourceFromTemplate` to fetch template and dispatch an associated template creation action using `template.content.type`.
- [x] Discussion: add template type to `meta`. Shouldn't have to fetch the entire template content to know its type.
- [ ] Update client to include variable type in `ITemplate`.  https://github.com/influxdata/influxdb2-js/pull/93

**Comment by OfTheDelmer** [comment]
Going to wait after #12925
