### ISSUE TITLE
Add ability to add and remove labels from+to templates

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#13064]
Currently labels can only be assigned at template creation, 
As a user I should be able to add/remove edit labels on a template just like any other resource

- [x] Await changes from https://github.com/influxdata/influxdb2-js/issues/94

- [ ] Fix changes to inlinelabels to resolve #13108 
- [x] Handle add/remove for inline labels.

**Comment by kelwang** [comment]
the api change will be addressed here: https://github.com/influxdata/influxdb/issues/12937

**Comment by OfTheDelmer** [comment]
This should be ready after the client work
