### ISSUE TITLE
Reconcile orgView and config pages

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#13063]
As a user when I click on the settings, 
I see a tabbed page view of resources in my organization. 
Please follow orgView patterns instead of configurations patterns. 
This story includes moving some redux state from `orgView.resource` to top level `resource`

- [x] Variables
- [x] Buckets
- [ ] Telegrafs (https://github.com/influxdata/influxdb/issues/13201)
- [ ] Scrapers (https://github.com/influxdata/influxdb/issues/13198)
- [ ] Templates (https://github.com/influxdata/influxdb/issues/13196)
- [x] Tokens
- [ ] Members (https://github.com/influxdata/influxdb/issues/13197)

**Comment by ebb-tide** [comment]
settings should contain resources as described in https://github.com/influxdata/influxdb/issues/12941
