### ISSUE TITLE
Import Dashboard From Template Overlay fixes

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/influxdb#13203]
- [ ] Add scrollbar for cells/variables panel
- [ ] Possibly also add scrollbar for template cards
- [ ] Remove checkmark from selected template card
- [ ] Show empty text if there are no variables or cells
