### ISSUE TITLE
Polish Import Dashboard From Template UI

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/influxdb#13343]
![image](https://user-images.githubusercontent.com/15273162/55992985-c6995a00-5c62-11e9-9d01-d066733f6f04.png)

- [ ] Handle placement/overflow of text in the Template cards on the left 
- [ ] Polish text spacing/margins on righthand panel
- [ ] Make Dashboard name editable
- [ ] Make Variable value viewable (?)
