### ISSUE TITLE
Ability to re-arrange cards in query builder

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#13359]
- [ ] Cards should be able to be dragged left/right 
- [ ] Flux query should be re-arranged as well
- [ ] From (first card) cannot be moved
