### ISSUE TITLE
Move fetching/parsing Flux data into a WebWorker

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#13849]
In Chronograf 1.x, we changed our query fetching + parsing routines to happen within a WebWorker (separate thread). This change had substantial performance benefits, and we should bring those benefits to the 2.x UI as well.

Still, the specifics of the implementation meant that parsing query responses for large dashboards would still lock up the UI and cause jank (rendering at << 60 fps). In particular, we had a large communication overhead from copying query response data between the main thread and WebWorkers multiple times, which would block rendering on the main thread. So I would propose as requirements for this story:

- [ ] Should not copy large amounts of data between main thread and WebWorker
- [ ] Should fetch data in WebWorker, parse it, and transfer it to the main thread exactly once

These requirements are now feasible since we are parsing into the [vis library](https://github.com/influxdata/vis) `Table` format, which is columnar (and thus can be backed by a collection of transferable `ArrayBuffer`s).

And unrelated requirements, but also important:

- [ ] Requests being made within WebWorker should be cancelable
- [ ] Need ability to limit requests within WebWorker to some max number of CSV rows
