### ISSUE TITLE
Add scatterplot vis type

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#13870]
- [x] Add new view type to backend (will need to be deployed before any UI changes)
- [x] Use [scatterplot from vis library](https://influxdata.github.io/vis/?path=/story/xy-plot--scatterplot)
- [x] Enable selecting which columns get mapped to `x`, `y`, `fill`, and `symbol` aesthetics
   - See histogram for an example of this is done (histogram maps `x` and `fill` aesthetics) 
   - `fill` and `symbol` aesthetics are multiselect
   - `fill` aesthetic should default to the `fluxGroupKeyUnion`
   - `shape` aesthetic should default to `[]`
- [x] Should be able to select color scheme
- [x] Should be able to title X and Y axes
- [x] Should be able to set X and Y axis domains
- [x] Should be able to set X and Y axis prefix/suffixes
