### ISSUE TITLE
Add heatmap vis type

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#13871]
Depends on https://github.com/influxdata/vis/issues/25

- [ ] Add new view type to backend (will need to be deployed before any UI changes)
- [ ] Use [vis library heatmap layer](https://influxdata.github.io/vis/?path=/story/xy-plot--heatmap)
- [ ] Support selecting which `x` and `y` columns are used in the visualization
- [ ] Support selecting a sequential color schemes to use in the heatmap (will need some help from @alexpaxton or @mavarius for this)
- [ ] Support labeling x and y axis
- [ ] Support x/y axis prefix/suffixes
- [ ] Support setting x/y axis domains
