### ISSUE TITLE
Use meta.type parameter in templates to differentiate template types

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14116]
- [x] Add `meta.type` string to templates when creating them from a resource. currently only dashboard and task and variable

- [x] Add `meta.type` string to the static templates in static template repo. 

- [x] When user selects create dashboard from template, only display dashboard templates.  (we can't currently pass query parameter that filters templates, but we can filter list of templates by type.)

- When user selects create task from template, only display task templates.  (will be completed in https://github.com/influxdata/influxdb/issues/14067

- Display the type of the template on the templates index page. (will be completed in https://github.com/influxdata/influxdb/issues/14098)

**Comment by ebb-tide** [comment]
See https://github.com/influxdata/influxdb/issues/14081 for discussion and rationale
