### ISSUE TITLE
Refactor Scheduler and Executor

### ISSUE THREAD

**Issue by lyondhill** [influxdata/influxdb#14183]
__Proposal:__
Write a scheduler that is more independent of the task system and can be used as an open source standalone library.

__Current behavior:__
The current scheduler is very tightly coupled to tasks. In addition it is doing scheduling, logging, tracing, and error management and correction.

__Desired behavior:__
We would like a scheduler that only handled scheduling and is portable. 

__Alternatives considered:__
When writing the new scheduler we want to ensure that it is portable so we need to keep influxdb imports and requirements to a minimum. We don't want the scheduler user to have to import any other influx libraries.

The framework for this new scheduler is laid out in https://github.com/influxdata/influxdb/blob/master/task/backend/scheduler/scheduler.go
With the interfaces in there we should be able to write a self contained scheduler.

### Responsibilities

A scheduler is responsible for understanding a cron-like schedule and ensuring these are executed at the desired frequency. Each task has its own schedule. The scheduler SHOULD schedule task runs in order. That is, for each task, the scheduler MUST call `Executor#Execute` with monotonically increasing time.

```go
type SchedulableStore interface {
	// UpdateLastScheduled updates the instance identified by ID with the new time
	UpdateLastScheduled(context.Context, ID, time.Time)
}

// Schedulable is the interface that encapsulates work that
// is to be executed on a specified schedule.
type Schedulable interface {
	// ID is the unique identifier for this Schedulable
	ID() ID

	// Schedule defines the frequency for which this Schedulable should be
	// queued for execution.
	Schedule() Schedule

	// Offset defines a negative or positive duration that should be added
	// to the scheduled time, resulting in the instance running earlier or later
	// than the scheduled time.
	Offset() time.Duration

	// LastScheduled specifies last time this Schedulable was queued
	// for execution.
	LastScheduled() time.Time
}
```

### TODOs

- [ ] Implement decoupled `NewScheduler` (naming) to replace `TickScheduler`
    - Will implement the `scheduler.Scheduler` interface
- [ ] Add unit tests for `NewScheduler`
    - [ ] Mock `Schedulable`
    - [ ] Mock `Executor`
- [ ] Create `type Time interface`
    - this type will be used to provide time to the `NewScheduler`
    - will be mockable for unit testing
- [x] Implement Cron parser to extended functionality

### Responsibilities

The executor is responsible for maintaining the concept of two queues to keep track of scheduled and running work. If the executor is restarted it MUST be capable of resuming outstanding work.

Each time `Execute` is called, it is the executors responsibility to queue the work and ensure this request is durable.

### TODOs

- [x] Define `scheduler.Executor` interface
    - The executor defines behavior to execute arbitrary tasks
    - Consumed by `NewScheduler` to execute tasks
- [x] Implement `TaskExecutor`, which conforms to `scheduler.Executor`
    - Initial implementation only knows how to execute Flux to queryd
- [x] Update `TaskControlService` to expose new APIs to handle `Executor` CRUD operations
- [ ] Implement single task concurrency limit
    - Required feature from existing `TickScheduler`
- Implement additional rate limits (max per organization?)
    - perhaps this is solved by executing Flux queries through gateway (rate limiting)
- [ ] Persist `Execute` state for recovery

### Guarantees

It is guaranteed that a task will be scheduled _at least once_. However, it is possible that the `Scheduler` may call `Execute`, and then fail to call `UpdateLastScheduled`. On restart it would attempt to reschedule the task for the same time. It is the responsibility of the executor to handle this case if it must not run certain tasks more than once.

### TODOs

- [ ] Define expected errors when calling `Executor#Execute`
    - All errors require well-defined documentation for when and why they should be returned
    Example errors
    - `ErrRetry` is the error returned by the executor to indicate it is unable to execute the work due to exceeding various limits (e.g concurrency, per-org, per-task) and should be retried later. That means the scheduler should not advance the `LastScheduled` time and defer execution to some later time.
    - `ErrUnrecoverable` is the error returned by the `Executor#Execute` for tasks that cannot be executed and require human interaction to be restarted (bad data). It is the responsibility of the `Executor` to signal that the task must be deactivated. It is expected that the `Scheduler` will receive a separate call to remove the task from its schedule.

## Coordinator

- [ ] Implement `NewCoordinator` to interact with `NewScheduler`
- [ ] **Cloud:** Implement `NewConsumer`
- [ ] Define feature flag to switch between existing `Coordinator` and `NewCoordinator`

**Comment by lyondhill** [comment]
this should solve #13358

**Comment by zhulongcheng** [comment]
Hi @lyondhill 
Can the new scheduler be used to schedule scrapers and alerts?

// coming soon: alerts and notifications.  https://www.youtube.com/watch?v=hgktF3kpgcE
