### ISSUE TITLE
Move API client generation into influxdb

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#14482]
See [RFC](https://github.com/influxdata/idpe/pull/4116) for motivation.

- Generate an API client and types from the `http/swagger.yml` spec and [oats](https://github.com/chnn/oats)
- Replace all usages of the `@influxdata/influx` package to use this generated code

### Remaining work

- [ ] Use locally generate API utils
  - [x] `client.auth` (https://github.com/influxdata/influxdb/pull/14611)
  - [x] `client.authorizations` (https://github.com/influxdata/influxdb/pull/14831)
  - [x] `client.buckets`
  - [x] `client.dashboards` (https://github.com/influxdata/influxdb/pull/16438)
  - [x] `client.labels` (https://github.com/influxdata/influxdb/pull/16361)
  - [x] `client.links`
  - [x] `client.organizations`
  - [x] `client.queries`
  - [ ] `client.scrapers`
  - [ ] `client.setup`
  - [x] `client.tasks` (https://github.com/influxdata/influxdb/pull/16353)
  - [ ] `client.telegrafConfigs`
  - [ ] `client.users`
  - [x] `client.variables` (https://github.com/influxdata/influxdb/pull/16400)
  - [x] `client.write`
  - [ ] `client.templates`
  - [x] `client.checks`
  - [x] `client.notificationRules`
