### ISSUE TITLE
Refactor overlays to use OverlayController pattern

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#15456]
Goal: refactor all overlays to match the pattern defined here https://github.com/influxdata/influxdb/pull/15368

The only existing example of this is the Note Editor within dashboards. This work should ideally be done piecemeal, so if you happen to work on an issue and touch code around an overlay, be the change and convert it to the new pattern.

#### Note:

- Make sure each overlay does not include the `Overlay` component (I know, counterintuitive)
  - `Overlay` wraps all overlays automatically by existing in `OverlayController`
  - The outermost component within each overlay should be `OverlayContainer`
- To prevent a flicker when opening an overlay, wrap `GetResources` around `OverlayBody` instead of `OverlayContainer`
- When handling overlays from the router, use this as an example:
  - https://github.com/influxdata/influxdb/blob/master/ui/src/index.tsx#L95-L100

#### List:

- [ ] #15464 Edit Endpoint
- [ ] #15465 New Endpoint
- [ ] #15466 Edit Rule
- [ ] #15467 New Rule
- [x] #15468 All Access Token
- [x] #15469 Read/Write Token
- [ ] #15470 View Token
- [ ] #15471 Create Bucket
- [ ] #15472 Update Bucket
- [ ] #15473 Client Library
- [x] Note Editor
- [ ] #15463 Delete Data
- [ ] #15474 Save As
- [ ] #15476 Create Label
- [ ] #15477 Update Label
- [ ] #15478 Add Members
- [ ] #15462 Create Organization
- [ ] #15479 Create Scraper
- [ ] #15480 Danger Confirmation
- [ ] #15481 Export Resource
- [ ] #15482 Import Resource
- [ ] #15483 View Resource
- [ ] #15484 Run Logs List
- [ ] #15485 Import Task from Template
- [x] #15486 Telegraf Config
- [ ] #15487 Create from Template
- [ ] #15488 Query Switcher
- [ ] #15489 Create Variable
- [ ] #15490 Update Variable
- [ ] #15491 View Editor (VEO)
- [ ] #15492 Check Editor (CheckEO)

**Comment by alexpaxton** [comment]
Bump

**Comment by russorat** [comment]
I think this work has completed. Closing.
