### ISSUE TITLE
[Monaco] Mega issue

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#15614]
#### First pass: (feature parity with current DE) 
- [x] https://github.com/influxdata/influxdb/issues/15635 Create feature flagged DE with monaco editor instead of code mirror
- [x] https://github.com/influxdata/influxdb/issues/15636 Integrate with query execution and receiving (plug it in)
- [x] https://github.com/influxdata/influxdb/issues/15637 Base theme for monaco from existing code mirror theme (background etc) cc : @alexpaxton 
- [x] https://github.com/influxdata/influxdb/issues/15638 Implement Scrollbars cc : @alexpaxton 
- [x] https://github.com/influxdata/influxdb/issues/15639 Describe syntax highlighting using Monarch for Monaco
- [x] https://github.com/influxdata/influxdb/issues/15640 Insert functions and variables on click and fixing #13727

#### Second pass:
- [ ] Add snippets (static auto completion)
- [ ] Use monaco everywhere we use code mirror or static code text- support syntax highlighting for each language: go etc.)

#### Third pass: (LSP WASM integration)
- [ ] Hover definitions on functions
- [ ] Intellisense / completion request
- [ ] Go to definition
- [ ] Errors on correct line numbers (Monaco displays ‘glyphs’ in margin https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin)
- [ ] data autocompletion (like a dynamic list of buckets)

#### Later:
- [ ] Yield data at breakpoint [...]
- [ ] Dropdown whenever r._measurement = [here]

**Comment by alexpaxton** [comment]
Exciting!

**Comment by russorat** [comment]
connect #16415
