### ISSUE TITLE
Auto Aggregation

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/influxdb#18813]
As a Data Explorer user, I should not be able write queries that crash the UI.

## Sequence
Based on the suggestion from @ebb-tide for review by @russorat 
1. Function Panel w/ aggregate mean, median (https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/17076)
2. New visualization (Band Chart in Giraffe) (https://github.com/influxdata/giraffe/issues/228)
3. Aggregate function mean, min, max (https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/18806)
4. Aggregate function: string (https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/18811)
5. Window Period (custom and Auto) & Tooltip (https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/18810)
6. Fill Mising Values (https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/18807)

## Acceptance Criteria

- [ ] User does not crash UI with queries in Data Explorer
- [ ] Data explorer queries aggregated automatically
- [ ] User can use Auto or Custom Window Periods and they're auto aggregated in the Data Explorer
- [ ] Window Periods cannot be so small as to create query crashing UIs in the Data Explorer
- [ ] String values can be auto aggregated in the Data Explorer
- [ ] Data sets with missing values are visually smoothed with `create:Empty: false ` in the Data Explorer

**Comment by russorat** [comment]
This epic has finished. Any remaining work should be picked up in a new epic.
