### ISSUE TITLE
Backport Flux pushdown rules to 1.9.0

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#21069]
1.x is missing these pushdown rules from 2.x:

- [x] FromStorageRule (implemented in #21074)
- [x] MergeFiltersRule (implemented in #21074)
- [x] PushDownWindowAggregateRule (implemented in #21124)
- [x] PushDownWindowAggregateByTimeRule (implemented in #21124)
- [x] PushDownBareAggregateRule (implemented in #21124)
- [x] GroupWindowAggregateTransposeRule (abandoned in #21161 - not yet stable enough to backport and off by default in 2.x)
- [x] PushDownReadTagKeysRule (needs sync'd with 2.x) - no longer in 1.9.0. See https://github.com/influxdata/influxdb/issues/21171 
- [x] PushDownReadTagValuesRule (needs sync'd with 2.x) - no longer in 1.9.0. See https://github.com/influxdata/influxdb/issues/21171
- [x] PushDownGroupAggregateRule (waiting on #20994) - done see https://github.com/influxdata/influxdb/pull/21281
