### ISSUE TITLE
Allow users to navigate between Accounts

### ISSUE THREAD

**Issue by corriganjohn** [influxdata/influxdb#21222]
GIVEN I am a user who is associated with more than one Account
THEN A new Navigation element is displayed for the Account
AND WHEN The user clicks that navigation element 
THEN A menu is displayed to allow switching between accounts

## Acceptance Criteria

- [ ] IF the user is associated with more than one account, a new clockwork navigation element is displayed
- [ ] If the user clicks the navigation element a flyout menu is displayed
    Menu displays

1. A new clockwork icon/indicator for the currently selected Account + the account Name
2. IF the current Account is the Default Account, the disabled text "Default Account"
3. IF the current Account is NOT the Default Account, a menu item to "Set Default Account"
4. [visual divider - horizontal line]
5. (non-clickable text) "Switch Accounts"
6. List of (clickable) Accounts the user can switch to
  - Clickable menu item contains small version of clockface account icon + Name of account

- [ ] IF the user selects 'Set Default Account' option
1. The currently selected Account is marked as being the Default Account
2. Display a notification alert "You have set {{AccountName}} as your default account during login"

- [ ] IF the user selects an account item from the menu
1. Switch to the selected Account
2. Display a notification alert "You have switched to {{AccountName}}"

## Design Prototype
https://www.figma.com/file/vjpHxTfM3IDAroqFiOr6mq/Navigation-Switch-Account-Mar-2021?node-id=3%3A96

### Design Epic
https://app.zenhub.com/workspaces/teamdesign-5f7e450d26b3010018884d96/issues/influxdata/design-resources/30

### Team
Platform Engineering - @aanthony1243 to assign
App Engineering Lead - @amesa@influxdata.com
Product - @russorat (inform @gunnaraasen )
Design - @corriganjohn

**Comment by daviddkkim** [comment]
May be a scope creep but great Idea brought up by Randy in the meeting: Make Account a part of the URL

**Comment by russorat** [comment]
IMO, we should keep the urls as generic as possible. things like /dashboards or /tasks, not /accounts/:id/dashboards.

**Comment by barbaranelson** [comment]
Can we move this epic to the UI repo? Makes more sense to be there, rather than in influxdb. Thanks.

**Comment by kristinarobinson** [comment]
@barbaranelson - I've written a possibly duplicate epic in the UI repo https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/ui/1287.  I based it off of this one.
