### ISSUE TITLE
Organization / Usage : Post-UI Unification Updates

### ISSUE THREAD

**Issue by corriganjohn** [influxdata/influxdb#21237]
GIVEN I am a user of InfluxDB Cloud
WHEN I want to check my Usage and associated Cost
THEN I go to the /Usage page and can see all Usage + Cost metrics clearly laid out

## Acceptance Criteria
- [ ] /Usage page is a Tabbed page under /Organization
- [ ] "Time Range' Is moved to the top of the page and affects all content
   - Add 'Billing Period' to dropdown of available time ranges (along with current: 24 hours / past 7 days / past 30 days)
- [ ] REMOVE 'Billing Stats' section
- [ ] ADD 'Total Cost' section
   - For FREE Accounts 
      1. display the text:  "You are on the FREE but limited use plan. These charges are provided as estimates of the unlimited Usage Based plan. See the **Usage Documentation** for more information on this data. " - [Usage Documentation] is a link to "https://docs.influxdata.com/influxdb/cloud/account-management/data-usage/"
      2. Display "Total Cost" with the (?) icon
      3. Display "FREE ({{estimated cost}})"
      4. On mouse-over on (?) display flyout menu with text "Charges are estimated based on the time frame selected and may differ from billing history. "
   - For PAYG Accounts
      1. display the text: "Please see our Usage Documentation for more details on usage and estimated cost. "
      2. (as Above)
      3. Display "{{estimated cost}}"
      4. (as above)

- [ ] Usage Panel
   - Title: "Usage - Past {{selected time period}}"
   - REMOVE dropdown to select a specific metric graph
   - Display ALL four metric graphs
      - Use a responsive column layout for all four graphs 
   - Individual Metric Panels (Data In / Data Out / Query Count / Data Storage) [Based on selected time period]
      1. Display metric chart (existing)
      2. ADD "Total {{metric type}}" and the total value for that metric
      3. ADD "Estimated Cost" and the estimated cost (in dollar amount to two decimal places)

- [ ] Rate Limits [NO CHANGES]
   - Title: "Rate Limits - Past {{selected time period}}"
   - Rate Limit Event Chart

## Design
FREE Plan
https://www.figma.com/file/86iuYYVcMvOIAXzy495Fvp/Usage-Q2-2021?node-id=1766%3A61

PAYG 
https://www.figma.com/file/86iuYYVcMvOIAXzy495Fvp/Usage-Q2-2021?node-id=1766%3A100

**Comment by corriganjohn** [comment]
This work will be deferred --- Usage Dashboard may potentially replace this need.
