### ISSUE TITLE
Cross-data-node pushdown merge support backports for InfluxDB 1.9

### ISSUE THREAD

**Issue by lesam** [influxdata/influxdb#21337]
The following PR's should be back ported to 1.9:

- [x]  chore: refactor to make it easier for enterprise to share functionality (#21309)
- [x]  feat: mean,count aggregation for WindowAggregate pushdown in enterprise (#21291)
- [x] fix: summation should be in native type for mean,count iterator (#21334)
- [x] [start, end] time fix to master-1.x (https://github.com/influxdata/influxdb/pull/21347)
- [x] [start, end] time fix to 1.9 https://github.com/influxdata/influxdb/pull/21348

**Comment by lesam** [comment]
Everything back ported successfully
