### ISSUE TITLE
Edge MVP

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24553]
The Edge MVP should be able to do the following:

1. Accept writes to `api/v3/write_lp` with line protocol
2. Respond to FlightSQL queries
3. Respond to `api/v3/query_sql` and return data in pretty print, json lines, csv, or arrow buffer
4. Persist buffered Catalog to configured object store (can be configured to point at local disk) 
5. Persist buffered data as Parquet files in object store (can be configured to point at local disk)
6. Optionally write buffered data into a WAL on locally attached disk, which can be recovered from
7. Bearer token all-or-nothing auth optionally configured

I'll write all of this up in more detail over the following weeks. For now here's a high level task list:

```[tasklist]
### Tasks
- [x] Fix CI, ensure Docker images building
- [ ] https://github.com/influxdata/influxdb/issues/24554
- [ ] https://github.com/influxdata/influxdb/issues/24555
- [ ] https://github.com/influxdata/influxdb/issues/24557
- [ ] https://github.com/influxdata/influxdb/issues/24558
- [ ] https://github.com/influxdata/influxdb/issues/24556
- [ ] https://github.com/influxdata/influxdb/issues/24661
- [ ] https://github.com/influxdata/influxdb/issues/24651
- [ ] https://github.com/influxdata/influxdb/issues/24643
- [ ] https://github.com/influxdata/influxdb/issues/24644
- [ ] https://github.com/influxdata/influxdb/issues/24645
- [ ] https://github.com/influxdata/influxdb/issues/24647
- [ ] https://github.com/influxdata/influxdb/issues/24653
- [ ] https://github.com/influxdata/influxdb/issues/24704
- [ ] https://github.com/influxdata/influxdb/issues/24681
```

**Comment by mgattozzi** [comment]
Checked of that CI was fixed with PRs:
#24562
#24563
#24564 
#24566

**Comment by mgattozzi** [comment]
I put the wrong issue to close in my PR. I've reopened it.

**Comment by mgattozzi** [comment]
Okay now we're done for real this time
