### ISSUE TITLE
Build, package, and sign binary builds, deb/rpms, and Docker for Releases

### ISSUE THREAD

**Issue by mgattozzi** [influxdata/influxdb#24773]
```[tasklist]
### Tasks
- [x] Build binaries for Windows, Mac, and Linux
- [x] Build release binaries for Windows, Mac, and Linux only on release
- [x] Have CI run the same on all platforms
- [x] Package builds into deb/rpms
- [x] Sign binary builds
- [x] Upload binary builds to s3
- [x] Create a docker build pipeline for release in the official images repo
```

**Comment by mgattozzi** [comment]
Note in https://github.com/influxdata/influxdb/pull/24769 @bnpfeife added the ability to cross build binaries on multiple platforms which is absolutely clutch. Thanks again @bnpfeife
