### ISSUE TITLE
Load generator improvements

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24827]
Some improvements to the load generator to help with testing and performance validation

```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb/issues/24828
- [ ] https://github.com/influxdata/influxdb/issues/24862
- [ ] https://github.com/influxdata/influxdb/issues/24831
- [ ] https://github.com/influxdata/influxdb/issues/24829
- [ ] https://github.com/influxdata/influxdb/issues/24832
- [ ] https://github.com/influxdata/influxdb/issues/24833
- [ ] https://github.com/influxdata/influxdb/issues/24861
```

**Comment by hiltontj** [comment]
All the issues above are complete, so I am closing this one out.
