### ISSUE TITLE
Investigate performance for single series queries

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24863]
I'd like to perform a set of changes and tests along with them to determine the lower bounds of performance for single series queries. The data set to test with is the [`one_mil` dataset in the load generator](https://github.com/influxdata/influxdb/blob/main/influxdb3_load_generator/src/specs/one_mil.rs). We may want to change this or simplify it later, but the brief description is that it is a data set with a single measurement containing all data with 1 single tag with cardinality of 1M, 10 randomly generated float field values, and 10 randomly generated integer float values.

The query being executed is the one in the spec that gets the data for values matching a tag id of a specific series. The number of rows these tests will be in the 1M to 10M range in most cases and potentially up to 100M. I think that since the largest set will only have at most 100 rows returned in the result, the amount of data returned will have a negligible impact on performance numbers. What matters is how quickly the query engine can find the requested 1 to 100 rows out of the bulk of data and return them via the API.

Some of the goals are to determine:

- How does the growth of rows in this data set impact performance for queries against:
    - In memory Arrow RecordBatch
    - On disk Parquet file (as currently implemented, unsorted)
    - On disk parquet file sorted by the `series-id` tag (#24823 must be implemented to test this)
    - In memory Parquet file both sorted and unsorted variants (with already in-memory metadata)
    - Data spread across N Parquet files for different values of N (both on disk and in-memory tests)
- These changes will require either small modifications to the spec, or updates outside of InfluxDB:
    - Querying against the _series_id field (#24861 will need to be implemented for this)
    - Convert _series_id to be a tag and repeat the experiment
    - Implement StringView/BinaryView with _series_id as a bytes type and perform tests (will require #24845 and apache/arrow-rs#5374, talk to @alamb about the latter)

None of these tests should require deduplication or sorting, I want to determine the best case performance numbers in optimal scenarios first. This should inform how data will ultimately have to be physically organized and what potential secondary indexing structures we'll need to achieve our performance targets.
```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb/issues/24866
- [ ] https://github.com/influxdata/influxdb/issues/24867
- [ ] https://github.com/influxdata/influxdb/issues/24868
- [ ] https://github.com/influxdata/influxdb/issues/24903
- [ ] https://github.com/influxdata/influxdb/issues/24823
- [ ] https://github.com/influxdata/influxdb/issues/24897
- [ ] https://github.com/influxdata/influxdb/issues/24905
```

**Comment by pauldix** [comment]
I've done some initial set of tests and gathered some numbers from my M1 Macbook Pro. The first test was to write the `one_mil` data set into a single segment in memory (i.e. a single RecordBatch) with total rows of 1M to 10M in 1M increments. The resulting queries would return 1 to 10 rows. Here's a graph showing results:

![buffer_query](https://github.com/influxdata/influxdb/assets/4331/4e8ddec1-c072-42d6-8ce5-bd2b638b4712)

That shows there's a fairly linear increase of about 24ms of response time for each 1M rows added to the source set. This tells me that for unsorted data in Arrow, to get response times in sub-100ms, we'll want to be able to narrow the data set we're evaluating against in a single series queries to no more than 4M rows.

The next test was the same row counts and queries, but this time in a single Parquet file unsorted. I wrote the data into the buffer and had it persist to Parquet and then queried against the data set, which then contained the single parquet file and no in memory data.

![parquet_query](https://github.com/influxdata/influxdb/assets/4331/41f9c69b-d051-4498-942a-bdadb47382e9)

That also shows an increase, but it isn't as consistent as the data in memory. I expanded the test to go up to 15M rows to see what kind of impact that would have as you can see in the chart above. I'd really like to see the result of this test against a Parquet file that is already in memory along with the metadata and also with just metadata in memory and Parquet file on local disk.

Lastly, I did a test with 10M rows of the one_mil data set, but spread out across 1 to 10 individual non-overlapping Parquet files.

![number_parquet_files](https://github.com/influxdata/influxdb/assets/4331/3f1ce2b2-b917-4964-9bc9-a97effa1bf05)

Interestingly, the number of Parquet files didn't seem to have a significant impact on the query performance in this test. Out of curiosity, I set the generator to put a bunch of data in spread out across many segments (i.e. individual parquet files) to see what that performance would look like. I didn't create a graph for this, but here's the info for two tests:

- 51M rows across 154 files: response times: median: 579ms, min: 542ms, max: 612ms
- 26M rows across 27 files: response times: median: 323ms, min: 289ms, max: 355ms
- 13M rows across 15 files: response times: median: 193ms, min: 176ms, max: 218ms

The number of rows seems to be the thing that dominates query response times, not the number of files. I expected number of files to have a bigger impact so I think this deserves some more investigation.

**Comment by alamb** [comment]
> The next test was the same row counts and queries, but this time in a single Parquet file unsorted. I wrote the data into the buffer and had it persist to Parquet and then queried against the data set, which then contained the single parquet file and no in memory data.

Another interesting experiment would be to first sort the parquet files (so the min/max statistics could be more helpful)

> The number of rows seems to be the thing that dominates query response times, not the number of files. I expected number of files to have a bigger impact so I think this deserves some more investigation.

I don't understand this conclusion from your data -- it seems like **BOTH** the number of rows and the number of files increased, right?

**Comment by pauldix** [comment]
The third set of graphs kept the number of rows constant at 10M and spread them out over varying numbers of files. The number of files didn't seem to impact the response time. Then after that, I ran a test to with many more rows across many more files, and then reduced row count and file count twice more. The reductions in response times in those tests tracked with both the reduced number of rows and reduced files (sadly, because of my test setup I changed both those variables at the same time). So more testing is needed. Doing the test on sorted files is definitely one of the next steps.

**Comment by pauldix** [comment]
I hacked up a quick and dirty index in the buffer which maps the series ID to the set of rows it appears in. Surprisingly, this didn't have a terrible impact on the RAM footprint. 

I then looked at the filters for a query and if it was filtering by the thing in the index, it would construct a record batch consisting of only those rows that gets yielded back to the query engine.

I tested this with 1M to 30M rows in the buffer (still the 1M series) all in one big record batch:
![buffer_with_index](https://github.com/influxdata/influxdb/assets/4331/44cac038-5f45-4d38-b2d4-2f3fecffdd1e)

You can see the response times going up a bit, but the queries are also returning an extra row on each run given more matching (i.e. 1 row returned for the first and 30 rows returned for the last). I should re-run the test with the query returning a fixed number of rows to see how the response times creep up.

In any case, this technique would make it possible to do very fast single series lookups even in large buffers before they get sorted and de-duped as Parquet.

**Comment by alamb** [comment]
> In any case, this technique would make it possible to do very fast single series lookups even in large buffers before they get sorted and de-duped as Parquet.

Nice!

Would it be possible to use the `series_id` index in the unpersisted buffer but not actually persist the series_id in parquet? That would be a pretty neat setup

**Comment by pauldix** [comment]
Using the comparison app in #24889 I ran for five minutes against the non-index buffer and the buffer with an index. You can see the query response times moving up quickly in the non-index case:
![Screenshot 2024-04-04 at 7 37 12 PM](https://github.com/influxdata/influxdb/assets/4331/c2eef001-d969-4790-875d-2076e4d28c94)

**Comment by deanasheehan** [comment]
@pauldix to make sure I am clear on your comparison.

Your very first graph is kinda the situation now (ignoring S3 etc), this is just the time it takes to scan through the rows to pick out the small number it actually requires out of a much larger set (where the content is unsorted and therefore all rows must be examined).

<img width="685" alt="image" src="https://github.com/influxdata/influxdb/assets/8803362/c28153bd-f30a-42cf-90a4-b48f349ed2bc">

And its alternative graph if you have a hacked up index that takes to you the specific rows:

<img width="654" alt="image" src="https://github.com/influxdata/influxdb/assets/8803362/83dfe6d9-d036-456e-a14a-bac04d032eb5">

Taking the 10M data set then we are looking at 20something ms v 230ish ms. Just want to make sure I am drawing the same conclusions.

This wouldn't be too surprising, but good to confirm with some real testing as you have done.

In persisted parquet (L1+ is that?) the the data is sorted isn't it? This would mean that on average a scan for a defined tag for 1 series of 10M in unsorted would be loosely equiv to 1 series of 5M if sorted (back of the envelope statistics). However, this sorting might also benefit your index - as I assume in the unsorted form you are indexing to each row of each series whereas in sorted you would index to the start of contiguous set (would that be a Parquet Row Group?) rows. Fair comment? Just checking i'm following :-)

**Comment by pauldix** [comment]
This work is largely complete. Optimizations have moved into the file index in Pro.
