### ISSUE TITLE
Benchmark sort/deduplicate on some data sets with 1-15 tags and with different cardinalities

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#24919]
This issue is for tracking performance deltas during sort/deduplication of persisted data (in parquet files) that result from introducing the `_series_id`.

### Requirements

```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb/issues/24920
- [ ] https://github.com/influxdata/influxdb/issues/24921
- [x] sort/dedup performance test: `_series_id` vs. tags for 1-15 tags at 10k cardinality
- [x] sort/dedup performance test: `_series_id` vs. tags for N tags at 10k cardinality for 1-10 files
```

**Comment by hiltontj** [comment]
I ran a series of tests to assess the impact on compaction performance of the `_series_id` column.

## Methods

I created a new sub-command in the load generator, `compact`, to perform these tests. That can be seen in this PR: https://github.com/influxdata/influxdb/pull/24925

The `compact` sub-command was run, in a release build, for the combination of the following input parameters:

Input | Description
-- | --
N<sub>tags</sub> | 1, 2, …, 15
Cardinality | 10000
N<sub>files</sub> | 10
N<sub>rows</sub> | 1000000
N<sub>threads</sub> | 1, 2, 4
Seed | 0, 1, …, 9
Series ID | true, false

This resulted in a total of 900 test runs. The primary comparison is the with/without `_series_id` performance as N<sub>tags</sub> increases. This was run for different seeds to factor some confidence into the generated results, and also with varying thread count to see if that impacted performance in either case.

## Results

![compact_test_1](https://github.com/influxdata/influxdb/assets/6188834/f0ebbb4e-97e6-4c6a-b1b7-1216ed45c520)

## Discussion

* The `_series_id` improves compaction performance as N<sub>tags</sub> increases
* However, performance still degrades as N<sub>tags</sub> increases with the use of `_series_id`, but at a lesser rate than without
* Without `_series_id` performance is better for less than 3 tags
* With `_series_id` seems to get better gains from increasing thread count; this may be worth trying at a higher thread count

The sampling interval used in these tests was 1 second. Although that does not have any impact on the result, it is worth discussing. The data generated for the above therefore represents 10,000 unique time series generating samples every second. So, with each file containing 1,000,000 rows, this would be only 100 seconds worth of data for every file. So, a difference in compaction time of 1 second or more is substantial; and this would be even more so on a tighter sampling interval.

**Comment by pauldix** [comment]
What was the base string used for the tags? I suspect that the length of the tag values could have significant impact on this performance. Worth running again with tag value strings that are 5, 15, 30, 60 characters in length (or thereabouts).

**Comment by hiltontj** [comment]
> What was the base string used for the tags?

The base was `value-`, so values would be, `value-0`, `value-1`, ..., `value-(N-1)`, where N is the cardinality.

I will expand upon this with the following:

* Generate results for 100k cardinality
* Try different tag lengths
* Track maximum memory usage during compaction

I will cut down the number of tags by using a sparser range, e.g., 1, 2, 5, 7, 10, 12, 15, and might also reduce the number of seeds used, because the results don't seem to vary much with seed. This should generate results a bit quicker.

**Comment by hiltontj** [comment]
I ran the test with 100k cardinality, here is the result next to the 10k cardinality result, running on 4 threads:

![compact_test_card](https://github.com/influxdata/influxdb/assets/6188834/f6afe0e2-f3c1-4378-8005-9e8ffb95ae5c)

**Comment by hiltontj** [comment]
I set it up to track memory usage, and to also run on a variable tag length.

Without the `_series_id`, once it gets to 7 tags, with a base length of 30, the compactor OOMs, with what looks like a DF error:
```
ResourcesExhausted("Failed to allocate additional 5853944 bytes for ExternalSorterMerge[0] with 0 bytes already allocated - maximum available is 1304316")
```
However, when using the `_series_id`, it does not experience this problem, and keeps chugging along.

The default memory pool size is 8 GB. I may increase that here for the sake of these tests, but that may present one clear advantage to using `_series_id`. I am assuming that with `_series_id`, the compaction planner only needs to look at `_series_id` and `time`, and so can be much more space efficient.

I am going to make some changes to the `compact` test to see if I can trim down the memory usage outside of the compaction planner itself, and then try this test run again to see if that helps. Otherwise I will just increase the size of the memory pool.

**Comment by pauldix** [comment]
Interesting, can't wait to see the memory results on these tests 😁

**Comment by hiltontj** [comment]
I ran the `compact` test, with memory usage tracking, for a tag base length of 15 and 30 characters, 100k and 1M cardinality.

Each graph below shows compaction time in the top row, and maximum memory usage in the bottom row.

From what I can tell, it looks like cardinality is not affecting compaction time, or max memory usage. The trend for the 10k cardinality runs was very close to what is below.

### Cardinality: 100k

![comp_100k_tag_len](https://github.com/influxdata/influxdb/assets/6188834/b3aeea86-1b0c-41dc-859e-f159bbc54462)

### Cardinality: 1M

![comp_1M_tag_len](https://github.com/influxdata/influxdb/assets/6188834/00f03783-d53d-4b2a-86dc-534c22ff7f12)

**Comment by hiltontj** [comment]
I edited my previous comment. Clearly, the cardinality does affect the memory usage. In the `tag_base_len=15` case, the max memory usage is multiple GB higher in the 1M cardinality case compared to the 100k case.
