### ISSUE TITLE
Introduce the v3 line protocol

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25032]
This issue is for tracking and planning the introduction of the v3 line protocol, along with the series key feature to InfluxDB 3.

The series key was originally proposed in https://github.com/influxdata/influxdb/issues/24979.

The v3 line protocol has been introduced experimentally to IOx, so will need to be ported into `influxdb3_core` to be used.

```[tasklist]
### Tasks
- [x] Setup a branch in `influxdb3_core` containing the experimental changes to support a series key in the core crates (see https://github.com/influxdata/influxdb3_core/pull/23)
- [ ] https://github.com/influxdata/influxdb/issues/25031
- [ ] https://github.com/influxdata/influxdb/issues/25033
- [ ] https://github.com/influxdata/influxdb/issues/25034
- [ ] https://github.com/influxdata/influxdb/issues/25036
- [ ] Support v3 write API in `influxdb3_client`
- [ ] Support v3 write API in `influxdb3_load_generator`
```

**Comment by pauldix** [comment]
Closing this for now as the ideas for the v3 data model will be revisited later.
