### ISSUE TITLE
Refactor WAL & Write Buffer to not require local storage

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#25142]
The WAL and Write Buffer need to be refactored to use a single WAL for all incoming data, which should be stored on the configured object store. Currently, a separate WAL, called a Segment is opened for each period of time that the written data lines up with (i.e. 10 minute segments and data timestamps bucket it into the WAL that matches that). We also currently limit the number of open segments to 100, limiting the time range of data that can be written.

There are a number of needs driving this refactor:
* Events other than individual data writes need to be logged into the WAL and when these events happen doesn't necessarily match the data timestamps
* Storing the WAL on object store gives the software the ability to support full data durability with no attached storage (i.e. the process can disappear and show up on another machine and pick back up where it left off)
* There are a number of features in Pro requiring this setup

This will require a change to how the WAL is organized and thus its format. So we'll also take the opportunity to refactor some of the file structure on object storage and the information that gets stored in the WAL to enforce every database, table, and column to have a u64 identifier, which can be used in the in-memory data structures and as part of the object store paths.

## High Level Design
This is a brief description of the high level design. Issues for each task will include more specific details of the underlying implementation. All data coming into the server will be written into a single WAL with each operation having a u64 monotonically increasing sequence number. In order for this to work against object storage, WAL writes will happen as individual files that get PUT into object storage. Those individual files will be identified by a separate monotonically increasing u64 sequence number. By default, one of these WAL files will be created each second (known as the WAL flush interval).

As individual write requests come into the API they will be validated against the in-memory Catalog and held in the WAL flush buffer, which ticks every second. After the flush of that buffer to a file on object store, success responses are sent to all clients. The implication of this is that write response times to this API will be anywhere from a few milliseconds to just over a second. The flush interval could be shortened by configuration, but likely no less than 100ms.

We will have another API endpoint that clients can write to that performs validation and buffering, but returns immediately before waiting for the WAL buffer flush. The drawback to using this API is that there is a potential window of data loss if the server goes down before the flush is successful or if the object store is unavailable. The other API would either time out or return an error to the client.

The WAL will be configured with a snapshot interval, N, which specifies how many files to remove. The server will wait for N + N/2 WAL files to be created. Once this has occurred it will snapshot the in-memory write buffer, splitting up the data into everything to be persisted (anything with timestamp <= max timestamp || sequence number <= max from the 0-N wal files) and data to be kept in the buffer (anything with sequence > max from 0-N WAL files and time > max timestamp from those files). This odd setup is to optimize for data to be persisted in non-overlapping blocks of time, if the lag of timestamps is less than the N/2 time interval.

The default for the snapshot interval will be 600, meaning that snapshots will occur every 10 minutes (1 per second, 600 seconds in that span) if the server receives writes every second of that time. When the snapshot runs it will persist the Catalog if any changes have occurred, persist Parquet files for any tables that have received writes, and write a snapshot file that indicates what files or other major operations occurred in those files that have been snapshot. 

```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb/issues/25144
- [ ] Define WAL Snapshot and update Persister to store and retrieve them
- [ ] Refactor Write Buffer from Segments to new WAL
- [ ] Update Catalog to keep identifiers for databases, tables, and columns
- [ ] Update Write Buffer to map in memory data with identifiers
- [ ] Update WAL structure to store numeric identifiers and string identifiers
```

**Comment by hiltontj** [comment]
I think the justification for this is solid and clear. I want to clarify my understanding about the snapshot process though:

> [...] This odd setup is to optimize for data to be persisted in non-overlapping blocks of time, if the lag of timestamps is less than the N/2 time interval.

When the snapshot kicks off, there are N + N/2 WAL files since the last snapshot. The excess N/2 files will not be removed after the snapshot is taken, but there are operations within the N/2 files that likely fall in the 0-N time range. The snapshot process will sift those out and have them persisted to Parquet etc. along with the operations from the 0-N files, then the 0-N files will be removed. N/2 should give enough leeway to ensure that all ops from the 0-N range are captured. That is my understanding.

Assuming that is correct, say we then fast forward in time to the next snapshot interval... we now have a new set of N + N/2 WAL files, however, in this case, the 0-N files contain operations that were sifted out in the previous snapshot - are those ignored?

**Comment by pauldix** [comment]
So the files and the structure of the buffer don't exactly match each other in the new setup. The buffer will organize data into 10m blocks of time. Say we start ingesting data around 2024-07-12T10:04 and we do so for 30 minutes. We'd have in the buffer (without snapshotting):

```
tableA
    2024-07-12T10:00
    2024-07-12T10:10
    2024-07-12T10:20
    2024-07-12T10:30
```

We would have for that period of time WAL files for every second from 10:04-10:34. Because writes come in from a variety of writers and the timestamps aren't strictly increasing, we'll frequently get out of order writes. But these are usually within seconds or a few minutes of each other.

Ideally, we want to snapshot at 10:15 persisting all data in the 10:00-10:10 block, then again at 10:25 and then 10:35, etc. To do this it won't exactly follow the formula I wrote up, I thought I'd figure out this details as I starting writing test cases. But I'll try to dig into it here.

On startup, we'll estimate when the first snapshot should run. So we startup at 10:04, round the clock to the nearest N * flush interval duration, and add half to that (arriving at 10:15). Take the difference from that time and 10:04 to get a timer for the first snapshot run (happens in 660 seconds). After that first run we have it run every N * flush interval (600 seconds).

Our goal with this process is to be able to persist Parquet files in those 10m blocks, without later persisting another file that overlaps with that time. =We find that the vast majority of our users follow the pattern of ingesting data around time "now" with some lagged collection in the seconds to couple of minutes range. That's what we want to optimize for. 

Obviously, this only works if data isn't being written all over time or with greater lag than N/2 seconds, so those users will end up having multiple Parquet files persisted for those blocks of time, which we should be able to handle, but not necessarily optimize in the near term. We also need to be able to handle if they write data in future times.

Back to our snapshotting run at 10:15. First, we want to find how many of the 0-N files we can snapshot based on the rule that data timestamp < 10:10. Loop through the files in order until you find one where that case doesn't hold up. All files before that index `i` can be culled in the snapshot.

We write a record to the WAL that we are snapshotting on that time and file index. We then split the buffer between all data < 10:10 and all data after. We persist all those buffers (parquet files) logging each in the WAL, write the snapshot summary file (also logging in the WAL), and then we delete all WAL files 0..i-1.

Because of lagged data collection, some of the WAL files that remain will have data that was already persisted in the snapshot. But because we logged the snapshot start in the log, we can handle this easily during WAL replay. We build up the buffer and when we see the snapshot start entry, we split it just like we would if it were being persisted. As we see the parquet persist entries, we clear those from the in-memory snapshot buffer, and then finally clean up the entire snapshot buffer on the summary entry.

The special case we'll need to handle is if data is being written to future times or if the clock of the server becomes inaccurate. In either case, we can choose to close the entire buffer and snapshot the whole WAL (i.e. persisting everything currently buffered and deleting all old WAL files). It's not optimal, but ensure that we don't have a WAL growing unbounded in the case of writes with future timestamps or system clock shenanigans.
