### ISSUE TITLE
Epic: Update Catalog database, table and column to have uint identifiers

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#25239]
In the Catalog, databases, tables, and columns should have uint identifiers. The database and table identifiers should be used in their object store paths. The primary motivation for this is so that we can support drop database and drop table with immediate reuse of those names without having to wait for the underlying object store data to get cleared out. The secondary motivation is to potentially enable a new write protocol later that would allow users to send only these IDs along with values, rather than string identifiers.

Individual WAL files should still be self describing, so any database, table or column ID that appears in the file should also be in the file with its string definition somewhere.

```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb/issues/25301
- [ ] https://github.com/influxdata/influxdb/issues/25375
- [ ] https://github.com/influxdata/influxdb/issues/25386
- [ ] https://github.com/influxdata/influxdb/issues/25403
- [ ] https://github.com/influxdata/influxdb/issues/25404
- [ ] https://github.com/influxdata/influxdb/issues/25405
- [ ] https://github.com/influxdata/influxdb/issues/25412
- [ ] https://github.com/influxdata/influxdb/issues/25413
```

**Comment by hiltontj** [comment]
@pauldix - this can probably be closed, but there is one more thing: since we are attaching IDs to things, it may also make sense to give last-value-caches an ID, instead of relying on a unique name.

However, I don't know that this is actually a requirement, since, unlike DBs/tables/columns, the last cache itself is not persisted in any way to disk, outside of its representation in the catalog. So, it would be safe to delete a last cache then recreate it with the same name but with a different configuration.
