### ISSUE TITLE
Utilize the in-memory parquet cache

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25347]
This epic is for tracking the use of the in-memory parquet cache: https://github.com/influxdata/influxdb/blob/2dae5c10935ac5389420cd69dc8f4c13731e6945/influxdb3_write/src/cache.rs#L21-L25

## Previous Issues

* https://github.com/influxdata/influxdb/issues/24897
* https://github.com/influxdata/influxdb/issues/24905

```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb/issues/25348
- [ ] https://github.com/influxdata/influxdb/issues/25349
- [ ] https://github.com/influxdata/influxdb/issues/25350
- [ ] https://github.com/influxdata/influxdb/issues/25369
- [ ] https://github.com/influxdata/influxdb/issues/25382
- [ ] https://github.com/influxdata/influxdb/issues/25383
- [ ] https://github.com/influxdata/influxdb/issues/25385
- [ ] https://github.com/influxdata/influxdb/issues/25392
- [ ] https://github.com/influxdata/influxdb/issues/25395
```

**Comment by hiltontj** [comment]
This is done!
