### ISSUE TITLE
Epic: send telemetry reports

### ISSUE THREAD

**Issue by praveen-influx** [influxdata/influxdb#25373]
This issue covers all the other issues that are needed for sending telemetry reports to the server

```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb/issues/25370
- [ ] https://github.com/influxdata/influxdb/issues/25371
- [ ] https://github.com/influxdata/influxdb/issues/25372
- [ ] https://github.com/influxdata/influxdb/issues/25418
```
