### ISSUE TITLE
Optimize server startup time

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25533]
```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb/issues/24604
- [ ] https://github.com/influxdata/influxdb/issues/25534
- [ ] https://github.com/influxdata/influxdb_pro/issues/236
```

**Comment by mgattozzi** [comment]
Everything in this Epic has been completed so I'm closing it now
