### ISSUE TITLE
Epic: Distinct Values Cache

### ISSUE THREAD

**Issue by hiltontj** [influxdata/influxdb#25539]
See the proposal issue here: https://github.com/influxdata/influxdb/issues/25538, which outlines the requirements for the feature, and is a good place to discuss the feature at a high level. Feel free to pose questions there or in any of the specific issues listed below.

```[tasklist]
### Issues
- [ ] https://github.com/influxdata/influxdb/issues/25543
- [ ] https://github.com/influxdata/influxdb/issues/25544
- [ ] https://github.com/influxdata/influxdb/issues/25546
- [ ] https://github.com/influxdata/influxdb/issues/25547
- [ ] https://github.com/influxdata/influxdb/issues/25545
- [ ] https://github.com/influxdata/influxdb/issues/25548
- [ ] https://github.com/influxdata/influxdb/issues/25582
- [ ] https://github.com/influxdata/influxdb/issues/25583
- [ ] https://github.com/influxdata/influxdb/issues/25647
- [ ] https://github.com/influxdata/influxdb/issues/25584
- [ ] https://github.com/influxdata/influxdb/issues/25564
```
