### ISSUE TITLE
Cluster updates

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#5168]
We're updating the clustering config to enable users to run the meta service on separate boxes than the main data nodes (or still run them together). Here's a list of things to get done.

### Implementation
- [x] Update metastore representation with flags for (raft, data node)
- [x] Can run InfluxDB with meta server enabled/disabled
- [x] Can run InfluxDB only with meta server (no data node, etc.)
- [x] Can add a new data node to the cluster
- [x] Can add a new server to the meta consensus group
- [x] Can remove a server from the meta consensus group
- [x] Logic to read node ID from file
- [x] Update node bind addresses if different
- [x] Update node info to have raft bind address, metaservice bind address, API bind address, data bind address
- [x] Remove server from Raft group
- [x] Remove server from the data group
- [x] UpdateNodeInfo with (is data node, is raft node)
- [x] Update ShardCreation to only use data nodes
- [x] Implement meta client
- [x] Kill anywhere that's using meta.Client.IsLeader
- [x] Move peers.json logic out to root so data nodes and metaservice nodes can both use
- [x] Can start up the metaservice with a snapshot file

### Testing
- [ ] Create single server, add 3 meta servers, remove meta from the running server, which should now only act as a data node
- [ ] Create 3 server cluster running both raft and meta, bring down/up while writing querying, ensure operation
- [ ] Create meta node server, add 5 data nodes, ensure that queries/writes work when various data nodes are failing
[ ] Create 3 meta servers, add 5 data nodes, ensure that queries/writes work when meta servers start failing

@dgnorton @corylanou

**Comment by pauldix** [comment]
### Document Config Changes
* hostname is no longer supported in the config or as a command line arg, use bind address
* dir added to top level
* bind address moved to top level (for raft and other tcp services)
* we now use bind-address to specify the hostname
* meta.raft-promotion removed
* data.enabled added
* meta.enabled added

### TODOs:
- [ ] Figure out how to upgrade. The applyAddNode command needs to be put back in. It should assume all nodes are meta and data, but we need to construct what the httpAddrs and tcpAddr is
- [ ] wire up changing a data node's host name
- [ ] update meta client to update its list of metaservers when metanodes changes. should update node file
- [ ] Check who uses VisitRetentionPolicies
- [ ] rebase from master
- [ ] fix backup/restore (wire up marshal binary)
- [ ] fix retention policy stuff to not keep the old shards and groups around
- [ ] fix the bind address logic to be able to pick up the hostname and work with binds like :8088 and 0.0.0.0:8088. Maybe hostname needs to be added back in?

**Comment by jwilder** [comment]
Remaining issues will be looked at in `0.11`.
