### ISSUE TITLE
Change how nodes ID's are assigned and associated meta data

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#5669]
Proposed solution is that each process, regardless of it's role as a meta, data, or both role, will get a single node id.

- [ ] Single Node IDs
- [ ] Separate node ID assignment from registration
- [x] Remove meta servers from node.json

Nodes are currently getting ID's as follows:

```
> show servers
name: data_nodes
----------------
id      http_addr       tcp_addr
3       localhost:8186  localhost:8188
4       localhost:8286  localhost:8288
6       localhost:8386  localhost:8388


name: meta_nodes
----------------
id      http_addr       tcp_addr
1       localhost:8291  localhost:8288
2       localhost:8191  localhost:8188
5       localhost:8391  localhost:8388
```
