### ISSUE TITLE
Clustering Startup/Configuration Clean up

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#5673]
This issue will serve as a top level tracker to clean up the remaining cluster configuration issues.

- [ ] Change how nodes ID's are assigned and associated meta data #5669
- [ ] Hostname/advertise address #5670
- [ ] Config + env var + command-line precedence #5671
- [ ] Cluster gossip/topology service #5672
- [x] Remove peers.json (move to in memory peers list)  - #5602 
- [ ] Remove MetaServers from node.json - #5695

**Comment by jsternberg** [comment]
Closing this since clustering is removed from the open source version.
