### ISSUE TITLE
Punchlist for v0.12.1 release

### ISSUE THREAD

**Issue by toddboom** [influxdata/influxdb#6245]
Make sure these items are merged and (if necessary), backported into the `0.12` branch before marking as completed.

- [x] Refresh admin assets (#6225)
- [x] Fix windows failure (#6260)
- [x] Functions miss data with a `WHERE` time clause (#6229)
- [x] Fix race on measurementFields (#6246)
- [x] Handle nil values from the tsm1 cursor correctly (#6239)
- [x] Fix IO issues caused by `CreateShardGroup` bug (#6259)
- [x] Throw an error when an invalid expression is used with aux iterators (#6258)

**Comment by e-dard** [comment]
@toddboom I have got this list up-to-date

**Comment by jsternberg** [comment]
Removed the protobuf package rename from this issue since the change that caused that rename to be necessary is only in master, not 0.12.

**Comment by toddboom** [comment]
@jsternberg should we be looking at #6262 for the "Functions miss data with a `WHERE` time clause" issue?

**Comment by jsternberg** [comment]
I just updated the top issue with the appropriate PR that goes into 0.12 for that one.

**Comment by jsternberg** [comment]
@toddboom we should be good for testing 0.12.1 and then doing the final release if all goes well.

**Comment by toddboom** [comment]
awesome, thanks!

**Comment by jsternberg** [comment]
The downloads page is updated with 0.12.1. I'm going to close this issue.
