### ISSUE TITLE
[[feature collection]] requested build and packaging enhancements

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6454]
This issue contains a list of related feature requests that are not on the near-term roadmap. The feature requests in this issue are all build and packaging features or configurations that have been requested. If you want to request a package not already listed please make a comment on this issue, and we will add it to the checklist.
#### OS support
- [ ] official Fedora package https://github.com/influxdata/influxdb/issues/1098
- [ ] SUSE package https://github.com/influxdata/influxdb/issues/1197
- [ ] FreeBSD package https://github.com/influxdata/influxdb/issues/2637
- [ ] Windows package https://github.com/influxdata/influxdb/issues/5359, https://github.com/influxdata/influxdb/issues/4219, https://github.com/influxdata/influxdb/issues/4452
- [ ] Alpine Linux https://github.com/influxdata/influxdb/issues/4997
- [ ] Amazon Linux https://github.com/influxdata/influxdb/issues/5035
#### Versioning enhancements
- [ ] make historical versions available from Homebrew https://github.com/influxdata/influxdb/issues/3241
- [ ] make historical versions available from `apt` repositories https://github.com/influxdata/influxdb/issues/5913
#### Configuration enhancements
- [ ] support for `.d` configuration files https://github.com/influxdata/influxdb/issues/3103
- [ ] Improve Debian uninstall https://github.com/influxdata/influxdb/issues/3347
- [ ] use upstart with Ubuntu Trusty https://github.com/influxdata/influxdb/issues/5209
- [ ] allow `rsync` mirroring https://github.com/influxdata/influxdb/issues/5066

**Comment by taoky** [comment]
Are there any updates about `rsync` mirroring? Although most of the issues mentioned here are only about InfluxDB 1.x packages, supporting `rsync` is obviously not a `1.x` only stuff, as it could benefit downstream mirroring Telegraf and InfluxDB 2.x packages.
